"""Ticker -> spoken coin name for every Bybit linear perpetual.

Generated 2026-08-23 from Bybit /v5/market/instruments-info (category
=linear, status Trading) crossed with CoinGecko /coins/markets (top
4000 by market cap; on symbol collisions the highest cap wins), plus
hand overrides for tokenized stocks and TTS-hostile official names.
Multiplier tickers (1000PEPE) speak the plain coin name; a ticker not
listed here is spoken as-is by speaker.spoken().
"""

COIN_NAMES = {
    "1000000BABYDOGE": "Baby Doge Coin",
    "1000000MOG": "Mog Coin",
    "10000NEX": "Nexus",
    "10000SATS": "SATS",
    "1000BONK": "Bonk",
    "1000BTT": "BitTorrent",
    "1000CAT": "Simon's Cat",
    "1000FLOKI": "FLOKI",
    "1000LUNC": "Terra Luna Classic",
    "1000NEIROCTO": "Neiro",
    "1000PEPE": "Pepe",
    "1000RATS": "Rats",
    "1000TAG": "TAGGER",
    "1000TOSHI": "Toshi",
    "1000TURBO": "Turbo",
    "1000XEC": "eCash",
    "2Z": "DoubleZero",
    "A": "Vaulta",
    "AAL": "American Airlines",
    "AAPL": "Apple",
    "ACE": "Fusionist",
    "ACH": "Alchemy Pay",
    "ACT": "Act I The AI Prophecy",
    "ACU": "Acurast",
    "ACX": "Across Protocol",
    "ADA": "Cardano",
    "ADBE": "Adobe",
    "AERO": "Aerodrome Finance",
    "AGI": "Delysium",
    "AGLD": "Adventure Gold",
    "AIO": "OlaXBT",
    "AIOZ": "AIOZ Network",
    "AKE": "Akedo",
    "AKT": "Akash Network",
    "ALCH": "Alchemist AI",
    "ALGO": "Algorand",
    "ALICE": "My Neighbor Alice",
    "ALLO": "Allora",
    "ALPINE": "Alpine F1 Team Fan Token",
    "ALT": "AltLayer",
    "AMAT": "Applied Materials",
    "AMDSTOCK": "AMD",
    "AMZN": "Amazon",
    "ANIME": "Animecoin",
    "ANKR": "Ankr Network",
    "APE": "ApeCoin",
    "APPSTOCK": "AppLovin",
    "APR": "Capricorn",
    "APT": "Aptos",
    "AR": "Arweave",
    "ARB": "Arbitrum",
    "ARC": "AI Rig Complex",
    "ARIA": "Aria.AI",
    "ARKM": "Arkham",
    "ARX": "ARCS",
    "ASP": "Aspecta",
    "ASR": "AS Roma Fan Token",
    "ASTR": "Astar",
    "ASTS": "AST SpaceMobile",
    "AT": "Apro",
    "ATH": "Aethir",
    "ATOM": "Cosmos Hub",
    "AUCTION": "Bounce",
    "AVAX": "Avalanche",
    "AVGO": "Broadcom",
    "AVNT": "Avantis",
    "AWE": "AWE Network",
    "AXL": "Axelar",
    "AXS": "Axie Infinity",
    "B": "BUILDon",
    "B2": "BSquared Network",
    "BABA": "Alibaba",
    "BABY": "Babylon",
    "BAC": "Bank of America",
    "BAN": "Comedian",
    "BANANA": "Banana Gun",
    "BANANAS31": "Banana For Scale",
    "BANK": "Lorenzo Protocol",
    "BARD": "Lombard",
    "BAT": "Basic Attention",
    "BB": "BounceBit",
    "BCH": "Bitcoin Cash",
    "BE": "Bloom Energy",
    "BEAT": "Audiera",
    "BEL": "Bella Protocol",
    "BERA": "Berachain",
    "BICO": "Biconomy",
    "BIGTIME": "Big Time",
    "BILL": "Billions Network",
    "BIO": "Bio Protocol",
    "BIRB": "Moonbirds",
    "BLEND": "Fluent",
    "BLUAI": "Bluwhale",
    "BMT": "Bubblemaps",
    "BNB": "Binance Coin",
    "BNC": "Bifrost",
    "BNT": "Bancor Network",
    "BOBA": "Boba Network",
    "BOME": "BOOK OF MEME",
    "BOT": "RoboStrategy",
    "BR": "Bedrock",
    "BREV": "Brevis",
    "BRKB": "Berkshire",
    "BROCCOLI": "CZ's Dog",
    "BSB": "Block Street",
    "BSV": "Bitcoin SV",
    "BTC": "Bitcoin",
    "BTR": "Bitlayer",
    "BTW": "Bitway",
    "C": "Chainbase",
    "C98": "Coin98",
    "CAKE": "PancakeSwap",
    "CASHCAT": "Cash Cat",
    "CATI": "Catizen",
    "CATSTOCK": "Caterpillar",
    "CC": "Canton",
    "CETUS": "Cetus Protocol",
    "CFG": "Centrifuge",
    "CFX": "Conflux",
    "CGPT": "ChainGPT",
    "CHILLGUY": "Just a chill guy",
    "CHIP": "USD.AI",
    "CHR": "Chromia",
    "CHZ": "Chiliz",
    "CKB": "Nervos Network",
    "CLANKER": "tokenbot",
    "CLO": "Yei Finance",
    "CLSK": "CleanSpark",
    "COAI": "ChainOpera AI",
    "COIN": "Coinbase",
    "COMP": "Compound",
    "COOKIE": "Cookie DAO",
    "COST": "Costco",
    "COW": "CoW Protocol",
    "CRCL": "Circle",
    "CRM": "Salesforce",
    "CRO": "Cronos",
    "CRV": "Curve DAO",
    "CRWD": "CrowdStrike",
    "CRWV": "CoreWeave",
    "CSCO": "Cisco",
    "CTC": "Creditcoin",
    "CTR": "Citrea",
    "CVC": "Civic",
    "CVX": "Convex Finance",
    "CYS": "Cysic",
    "DATA": "Data Network",
    "DBR": "deBridge",
    "DDOG": "Datadog",
    "DEEP": "DeepBook",
    "DKNG": "DraftKings",
    "DOGE": "Dogecoin",
    "DOLO": "Dolomite",
    "DOOD": "Doodles",
    "DOS": "DAPPOS",
    "DOT": "Polkadot",
    "DRAM": "Roundhill Memory ETF",
    "DRIFT": "Drift Protocol",
    "DYDX": "dY dX",
    "DYM": "Dymension",
    "EDEN": "OpenEden",
    "EDGE": "edgeX",
    "EDU": "Open Campus",
    "EGLD": "MultiversX",
    "EIGEN": "EigenCloud",
    "ENA": "Ethena",
    "ENJ": "Enjin Coin",
    "ENS": "Ethereum Name Service",
    "EPIC": "Epic Chain",
    "ERA": "Caldera",
    "ESP": "Espresso",
    "ESPORTS": "Yooldo Games",
    "ETC": "Ethereum Classic",
    "ETH": "Ethereum",
    "ETHBTC": "Ether Bitcoin ratio",
    "ETHFI": "Ether.fi",
    "EUL": "Euler",
    "EVAA": "EVAA Protocol",
    "EWT": "Energy Web Token",
    "F": "SynFutures",
    "FARTCOIN": "Fartcoin",
    "FF": "Falcon Finance",
    "FHE": "Mind Network",
    "FIDA": "Bonfida",
    "FIL": "Filecoin",
    "FLR": "Flare",
    "FORM": "Four",
    "GE": "General Electric",
    "GIGGLE": "Giggle Fund",
    "GILD": "Gilead",
    "GLM": "Golem",
    "GMESTOCK": "GameStop",
    "GOAT": "Goatseus Maximus",
    "GOOGL": "Google",
    "GPS": "GoPlus Security",
    "GRT": "The Graph",
    "GRVT": "GRVT Token",
    "GS": "GammaSwap",
    "GUN": "Gunz",
    "GWEI": "ETHGas",
    "H": "Humanity",
    "HAEDAL": "Haedal Protocol",
    "HANA": "Hana Network",
    "HBAR": "Hedera",
    "HD": "Home Depot",
    "HEI": "Heima",
    "HMSTR": "Hamster Kombat",
    "HNT": "Helium",
    "HOLO": "Holoworld",
    "HOOD": "Robinhood",
    "HPE": "HP Enterprise",
    "HUMA": "Huma Finance",
    "HYPE": "Hyperliquid",
    "HYPER": "Hyperlane",
    "ICNT": "Impossible Cloud Network Token",
    "ICP": "Internet Computer",
    "ICX": "ICON",
    "ID": "SPACE ID",
    "ILV": "Illuvium",
    "IMX": "Immutable",
    "IN": "INFINIT",
    "INIT": "Initia",
    "INJ": "Injective",
    "INTC": "Intel",
    "INX": "Infinex",
    "IO": "io.net",
    "IOTX": "IoTeX",
    "JASMY": "JasmyCoin",
    "JCT": "Janction",
    "JD": "JD.com",
    "JELLYJELLY": "Jelly-My-Jelly",
    "JNJ": "Johnson and Johnson",
    "JPM": "JP Morgan",
    "JST": "JUST",
    "JTO": "Jito",
    "JUP": "Jupiter",
    "KAS": "Kaspa",
    "KAT": "Katana",
    "KERNEL": "KernelDAO",
    "KMNO": "Kamino",
    "KNC": "Kyber Network Crystal",
    "KO": "Kyuzo's Friends",
    "KSM": "Kusama",
    "LA": "Lagrange",
    "LDO": "Lido DAO",
    "LGELECTRONICS": "LG Electronics",
    "LIGHT": "Bitlight",
    "LINK": "Chainlink",
    "LIT": "Lighter",
    "LLY": "Eli Lilly",
    "LPT": "Livepeer",
    "LQTY": "Liquity",
    "LRC": "Loopring",
    "LSK": "Lisk",
    "LTC": "Litecoin",
    "LUNA2": "Luna",
    "LYN": "Everlyn",
    "M": "MemeCore",
    "MA": "Mastercard",
    "MAGIC": "Treasure",
    "MAGMA": "Magma Finance",
    "MANA": "Decentraland",
    "MANTA": "Manta Network",
    "MARA": "Marathon Digital",
    "MASK": "Mask Network",
    "MAV": "Maverick Protocol",
    "MAVIA": "Heroes of Mavia",
    "ME": "Magic Eden",
    "MEGA": "MegaETH",
    "MELANIA": "Melania Meme",
    "MEME": "MEMETOON",
    "MERL": "Merlin Chain",
    "MET": "Meteora",
    "MEW": "cat in a dogs world",
    "MINA": "Mina Protocol",
    "MITO": "Mitosis",
    "MMT": "Momentum",
    "MNT": "Mantle",
    "MOCA": "Moca Network",
    "MON": "Monad",
    "MOODENG": "Moo Deng",
    "MOVE": "Movement",
    "MOVR": "Moonriver",
    "MRNA": "Moderna",
    "MRVL": "Marvell",
    "MSFT": "Microsoft",
    "MSTR": "MicroStrategy",
    "MTL": "Metal DAO",
    "MU": "Micron Technology",
    "MYX": "MYX Finance",
    "NAORIS": "NaoX Protocol",
    "NBIS": "Nebius Group N.V.",
    "NEAR": "NEAR Protocol",
    "NET": "NetNet",
    "NEWT": "Newton Protocol",
    "NFLX": "Netflix",
    "NIGHT": "Midnight",
    "NIL": "Nillion",
    "NMR": "Numeraire",
    "NOM": "Nomina",
    "NOT": "Notcoin",
    "NOW": "ChangeNOW",
    "NVDA": "Nvidia",
    "NXPC": "Nexpace",
    "O": "o1.exchange",
    "OG": "OG Fan Token",
    "OGN": "Origin Token",
    "ON": "Orochi Network",
    "ONG": "Ontology Gas",
    "ONT": "Ontology",
    "OP": "Optimism",
    "OPEN": "OpenLedger",
    "OPG": "OpenGradient",
    "OPN": "Opinion",
    "ORCL": "Oracle",
    "ORDER": "Orderly",
    "PANW": "Palo Alto",
    "PARTI": "Particle Network",
    "PAXG": "PAX Gold",
    "PDD": "Pinduoduo",
    "PENGSTOCK": "Penguin Solutions",
    "PENGU": "Pudgy Penguins",
    "PEOPLE": "ConstitutionDAO",
    "PEP": "Pepecoin",
    "PHA": "PHALA",
    "PIXEL": "Pixels",
    "PLTR": "Palantir",
    "PNUT": "Peanut the Squirrel",
    "POLYX": "Polymesh",
    "POPMART": "Pop Mart",
    "POWER": "Power Protocol",
    "POWR": "Powerledger",
    "PRL": "Pearl",
    "PROMPT": "Wayfinder",
    "PROVE": "Succinct",
    "PTB": "Portal to Bitcoin",
    "PUMPFUN": "Pump Fun",
    "PUNDIX": "Pundi X",
    "PYPL": "PayPal",
    "PYTH": "Pyth Network",
    "Q": "Quack AI",
    "QCOM": "Qualcomm",
    "QNT": "Quant",
    "QQQ": "Nasdaq QQQ",
    "RARE": "SuperRare",
    "RAVE": "RaveDAO",
    "RDDT": "Reddit",
    "RED": "RedStone",
    "REZ": "Renzo",
    "RIVN": "Rivian",
    "RKLB": "Rocket Lab",
    "RLC": "iExec RLC",
    "RLUSD": "Ripple USD",
    "ROBO": "Fabric Protocol",
    "ROSE": "Oasis",
    "RPL": "Rocket Pool",
    "RSR": "Reserve Rights",
    "RUNE": "THORChain",
    "RVN": "Ravencoin",
    "S": "Sonic",
    "SAFE": "SAFEbit",
    "SAHARA": "Sahara AI",
    "SAND": "The Sandbox",
    "SCRT": "Secret",
    "SENT": "Sentient",
    "SHELL": "MyShell",
    "SHIB1000": "Shiba Inu",
    "SHOP": "Shopify",
    "SKHY": "SK Hynix",
    "SKHYNIX": "SK Hynix",
    "SKL": "SKALE",
    "SKR": "Seeker",
    "SLP": "Smooth Love Potion",
    "SLX": "Solstice",
    "SMCI": "Supermicro",
    "SNDK": "Sandisk",
    "SNOW": "Snowflake",
    "SNT": "Status",
    "SNX": "Synthetix",
    "SOL": "Solana",
    "SOMI": "Somnia",
    "SONIC": "Sonic SVM",
    "SOPH": "Sophon",
    "SOSO": "SoSoValue",
    "SPACE": "Spacecoin",
    "SPCX": "SpaceX",
    "SPK": "Spark",
    "SPOT": "Spotify",
    "SPX": "SPX6900",
    "SPY": "S and P 500",
    "SSV": "SSV Network",
    "STG": "Stargate Finance",
    "STO": "StakeStone",
    "STRK": "Starknet",
    "STX": "Stacks",
    "SUN": "Sun Token",
    "SUPER": "SuperVerse",
    "SXT": "Space and Time",
    "SYRUP": "Maple Finance",
    "T": "Threshold Network",
    "TA": "Trusta AI",
    "TAO": "Bittensor",
    "THE": "Thena",
    "THETA": "Theta Network",
    "TIA": "Celestia",
    "TLM": "Alien Worlds",
    "TNSR": "Tensor",
    "TRB": "Tellor Tributes",
    "TRUMP": "Official Trump",
    "TRUST": "Intuition",
    "TRUTH": "Swarm Network",
    "TRX": "TRON",
    "TSLA": "Tesla",
    "TSM": "TSMC",
    "TTWO": "Take Two",
    "TUT": "Tutorial",
    "TWT": "Trust Wallet",
    "TXN": "Texas Instruments",
    "UAI": "UnifAI Network",
    "UB": "Unibase",
    "UNH": "UnitedHealth",
    "UNI": "Uniswap",
    "US": "Talus",
    "USAR": "USA Rare Earth",
    "USDE": "Ethena USDe",
    "USELESS": "Useless Coin",
    "USTC": "TerraClassicUSD",
    "V": "Vault",
    "VET": "VeChain",
    "VIRTUAL": "Virtuals Protocol",
    "VRTXSTOCK": "Vertex",
    "VVV": "Venice Token",
    "W": "Wormhole",
    "WAL": "Walrus",
    "WAXP": "WAX",
    "WCT": "WalletConnect Token",
    "WET": "HumidiFi",
    "WIF": "Dogwifhat",
    "WLD": "Worldcoin",
    "WLFI": "World Liberty Financial",
    "WMT": "Walmart",
    "XAG": "Silver",
    "XAN": "Anoma",
    "XAU": "Gold",
    "XAUT": "Tether Gold",
    "XCN": "Onyxcoin",
    "XDC": "XDC Network",
    "XLM": "Stellar",
    "XMR": "Monero",
    "XNY": "Codatta",
    "XOM": "Exxon",
    "XPIN": "XPIN Network",
    "XPL": "Plasma",
    "XRP": "Ripple",
    "XTZ": "Tezos",
    "XVG": "Verge",
    "XVS": "Venus",
    "YB": "Yield Basis",
    "YFI": "yearn.finance",
    "YGG": "Yield Guild Games",
    "ZBCN": "Zebec Network",
    "ZBT": "ZEROBASE",
    "ZEC": "Zcash",
    "ZEN": "Horizen",
    "ZEST": "Zest Protocol",
    "ZETA": "ZetaChain",
    "ZIL": "Zilliqa",
    "ZK": "ZKsync",
    "ZKC": "Boundless",
    "ZKP": "zkPass",
    "ZM": "Zoom",
    "ZRO": "LayerZero",
    "ZRX": "0x Protocol",
}
