sonar.projectKey=wansiedler_hyperliquid-sizer
sonar.organization=wansiedler
sonar.python.version=3.12,3.13,3.14
sonar.sources=.
sonar.exclusions=test_*.py
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml
